name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test

  package:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Create VSIX
        run: npx @vscode/vsce package --no-dependencies
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: theme-lab-vsix
          path: "*.vsix"

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish to Marketplace
        run: npx @vscode/vsce publish --pat $VSCE_PAT --no-dependencies
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
